### ISSUE TITLE
Hopefully innocuous warning

### ISSUE THREAD

**Issue by jennielu92** [NREL/PIDG#64]
This warning appears for unknown reasons, and then sometimes disappears as suddenly as it came.

Warning messages:
1: In rm(data.path, cur.data, excluded.cols, memb.cols, cur.args, elem) :
  object 'excluded.cols' not found
2: In rm(data.path, cur.data, excluded.cols, memb.cols, cur.args, elem) :
  object 'memb.cols' not found
3: In rm(data.path, cur.data, excluded.cols, memb.cols, cur.args, elem) :
  object 'cur.args' not found

Currently unclear how big of a problem it is.

**Comment by aliehlen1** [comment]
done in 13bc11
